const E=window.AigerEngine;let state=E.initial(),view='appliances',returnFocus=null;
if(!new URLSearchParams(location.search).has('demo'))document.querySelector('.scenario-panel').hidden=true;
const $=s=>document.querySelector(s);
const icons={fridge:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M6 10h12M9 6v2m0 5v3"/>',lights:'<path d="M8 16c0-3-3-4-3-8a7 7 0 0 1 14 0c0 4-3 5-3 8zM9 19h6m-5 3h4"/>',cooktop:'<rect x="2" y="4" width="20" height="16" rx="2"/><circle cx="8" cy="10" r="3"/><circle cx="16" cy="14" r="3"/>',hood:'<path d="M9 2h6v7l6 8H3l6-8zM5 20h14"/>',oven:'<rect x="3" y="2" width="18" height="20" rx="2"/><rect x="6" y="9" width="12" height="9" rx="1"/><path d="M7 5h1m4 0h1m4 0h1"/>',dishwasher:'<rect x="3" y="2" width="18" height="20" rx="2"/><path d="M3 7h18M7 12l2 6m3-6v6m5-6-2 6"/>'};
const names={fridge:'Refrigerator',lights:'Kitchen lights',cooktop:'Cooktop',hood:'Ventilation',oven:'Steam oven',dishwasher:'Dishwasher'};
const icon=k=>`<span class="device-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icons[k]}</svg></span>`;
const button=(label,type,extra='',kind='')=>`<button class="button ${kind}" data-action="${type}" ${extra}>${label}</button>`;
const intro=(title,description)=>`<div class="page-intro"><div><p class="eyebrow">INDEPENDENT LIVING, CONNECTED CARE</p><h1>${title}</h1><p>${description}</p></div>${modes()}</div>`;
const modes=()=>`<div class="mode-control" role="group" aria-label="Kitchen mode"><button data-action="mode" data-value="active" aria-pressed="${state.mode==='active'}" ${state.severity==='critical'?'disabled':''}>Active</button><button data-action="mode" data-value="standby" aria-pressed="${state.mode==='standby'}" ${state.severity==='critical'?'disabled':''}>Standby</button></div>`;
function detail(k){if(!state.devices[k])return 'Powered off';return {fridge:'4°C · Door closed',lights:'Lighting on',cooktop:state.pan?'Pan detected · '+state.heat+' heat':'Gas valve open · '+state.heat+' heat',hood:'Automatic ventilation',oven:state.ovenStage,dishwasher:state.dishStage}[k];}
function safetyBanner(){const critical=state.severity==='critical';const warning=['oil','dry','unattended','long-away','salt-repeat'].includes(state.event);const e=events()[state.event];const title=critical?({gas:'Gas alert detected',water:'Water detected',fall:'Possible fall detected'}[state.event]||'Kitchen needs attention'):e?e[0]:'All normal';const text=critical?'Automatic shutdown triggered. Assistance is being requested.':e?e[1]:'Safety monitoring stays on in standby.';return `<section class="safety-banner" ${critical||warning?'role="alert"':''}><span class="safety-symbol">${critical||warning?'!':'✓'}</span><div><h3>${title}</h3><p>${text}</p></div><span class="pill">${critical?'Alert active':warning?'Attention needed':'Monitoring active'}</span></section>`;}

function dashboard(){return intro('Your kitchen, at a glance.','A clear view of what’s on, what’s next, and when help is needed.')+safetyBanner()+`<div class="grid"><section class="card feature"><div class="card-top"><p class="eyebrow">COOKING COMPANION</p><span class="pill">${state.devices.cooktop?'Cooking active':'Ready when you are'}</span></div><h2>${state.devices.cooktop?'Stay focused on your cooking.':'A little support.<br>A familiar routine.'}</h2><p>${state.devices.cooktop?'Your cooktop and ventilation status stay visible as the kitchen responds.':'Place your pan. Cook your way. Get a clear reminder when it matters.'}</p><div class="cooktop-art" aria-hidden="true"><div class="hob-plate"><div class="hob-ring"></div></div></div><button class="button" data-view="cooking">${state.devices.cooktop?'View cooking status':'Open cooking assistance'} →</button></section><section class="card"><div class="card-top"><h2>Appliance overview</h2><span class="pill">6 devices</span></div><div class="device-list">${Object.keys(names).map(k=>`<div class="device-row">${icon(k)}<div class="device-text"><h3>${names[k]}</h3><p>${detail(k)}</p></div><span class="pill">${state.devices[k]?'On':'Off'}</span></div>`).join('')}</div></section></div><div class="section-label"><h2>Always within reach</h2><span>One clear action at a time</span></div><div class="quick-grid"><button class="quick-card" data-action="family"><span><b>Contact family</b><small>Voice & remote assistance</small></span>↗</button>${state.severity==='critical'?'':`<button class="quick-card" data-action="${state.mode==='off'?'restart':'shutdown-dialog'}"><span><b>${state.mode==='off'?'Restart kitchen':'Turn off all'}</b><small>${state.mode==='off'?'Manual restart':'Review shutdown options'}</small></span>→</button>`}<button class="quick-card danger" data-action="sos"><span><b>Emergency assistance</b><small>SOS · Get help</small></span>↗</button></div>`;}
const events=()=>({pan:['Pan detected','The gas valve has opened. Ventilation is ready in standby; it starts when ignition is detected.'],ignite:['Cooking has started','Ignition detected. The cooktop is on Low. Kitchen lights and ventilation have started automatically.'],warm:['Your pan is hot','A screen and voice reminder helps you notice the next cooking moment.'],oil:['Oil splatter detected','Heat has automatically reduced to Low. Ventilation is active.'],dry:['Pan may be drying out','Heat has automatically reduced to '+state.heat+'. Continued dryness reduces it again.'],unattended:['Kitchen unattended','Heat has automatically reduced to Medium-low.'], 'long-away':['Extended absence detected','Heat has reduced to Low. The original flow asks whether to turn it off, then does so after 30 seconds without a response.'],'salt':['Seasoning recorded','Salt has been added '+state.salt+' time(s). Open the record when you need to check.'],'salt-repeat':['Salt added 3 or more times','Please check the seasoning record before adding more.'],'off-confirmed':['Cooktop is off','The shutdown is reflected in the appliance status.'],oven:['Oven status updated',state.ovenStage],dishwasher:['Dishwasher status updated',state.dishStage],resolved:['Risk-cleared scenario','Appliances remain off. Restart manually before using the kitchen again.']});
function eventCard(){const e=events()[state.event];if(!e)return '';return `<section class="card event-card ${['oil','dry','unattended','long-away','salt-repeat'].includes(state.event)?'warning':''}" role="status"><p class="eyebrow">CONTEXT → VISIBLE RESPONSE</p><h2>${e[0]}</h2><p>${e[1]}</p></section>`;}
function cooking(){return intro('Cook your way.','The original sensing and appliance-response sequence, made easier to follow.')+eventCard()+`<div class="steps"><div><b>01 · Sense</b>Pan, heat, activity and seasoning inputs</div><div><b>02 · Interpret</b>Recognize the current cooking condition</div><div><b>03 · Communicate</b>Clear status, reminder or confirmation</div><div><b>04 · Act</b>Original automatic or user-controlled response</div></div><div class="grid"><section class="card"><p class="eyebrow">COOKTOP STATUS</p><h2>${state.devices.cooktop?'Cooking in progress':'Ready to begin'}</h2><div class="readout">${state.heat==='Off'?'Heat off':state.heat+' heat'}</div><p>${state.pan?'Pan present · Gas '+(state.gas?'open':'closed'):'Place your pan to begin the original sequence.'}</p><div class="actions">${button('Place pan','pan')}${button('Ignite cooktop','ignite','','secondary')}${button('Turn off heat','confirm-off','','secondary')}</div><div class="actions" role="group" aria-label="Cooktop heat">${['Low','Medium','High'].map(h=>button(h,'heat',`data-value="${h}" aria-pressed="${state.heat===h}"`,'secondary')).join('')}</div></section><section class="card"><p class="eyebrow">SEASONING MEMORY</p><h2>A small reminder,<br>when you need it.</h2><p style="margin-top:14px">Salt: ${state.salt} additions<br>Soy sauce: ${state.soy} additions</p><div class="actions">${button('View record','seasoning')}${button('Add salt · demo input','salt','','secondary')}</div></section><section class="card full"><p class="eyebrow">WHAT THE SYSTEM DID</p><ul class="log-list">${state.logs.length?state.logs.slice(0,5).map(t=>`<li>${t}</li>`).join(''):'<li>Use a cooking action or open the scenario controls below.</li>'}</ul></section></div>`;}
function appliances(){return intro('Your kitchen, at a glance.','Familiar routines. Clear controls. Support for independent living.')+safetyBanner()+`<div class="device-grid">${Object.keys(names).map(k=>`<section class="card">${icon(k)}<h2>${names[k]}</h2><div class="readout">${state.devices[k]?'On':'Off'}</div><p>${detail(k)}</p>${k==='fridge'?'<span class="pill">Maintained in standby</span>':button(state.devices[k]?'Turn off':'Turn on','toggle',`data-device="${k}" ${state.severity==='critical'?'disabled':''}`,'secondary')}</section>`).join('')}</div><div class="actions">${state.severity==='critical'?'':button(state.mode==='off'?'Restart kitchen':'Turn off all',state.mode==='off'?'restart':'shutdown-dialog','','secondary')}${button('View seasoning record','seasoning','','secondary')}</div>`;}

function safety(){return intro('Help is easy to find.','A clear response when the kitchen needs attention.')+safetyBanner()+`<div class="grid"><section class="card"><div class="support-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><circle cx="18" cy="16" r="7"/><path d="M5 39v-5c0-6 6-10 13-10s13 4 13 10v5M34 9a6 6 0 0 1 0 12m2 5c5 1 7 4 7 8v5"/></svg></div><p class="eyebrow">FAMILY & REMOTE SUPPORT</p><h2>You don’t have to<br>figure it out alone.</h2><p style="margin-top:14px">Contact someone you trust for a conversation or help with your kitchen.</p><div class="actions">${button('Contact family','family')}</div></section><section class="card"><div class="support-icon emergency-icon" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M24 4 40 10v13c0 10-8 17-16 21-8-4-16-11-16-21V10zM24 16v14m-7-7h14"/></svg></div><p class="eyebrow">EMERGENCY ASSISTANCE</p><h2>A direct route to help.</h2><p style="margin-top:14px">Reach family and emergency support with one clear action. You can cancel an accidental tap before the countdown ends.</p><div class="actions">${button('SOS · Get help','sos','','danger')}${state.severity==='critical'?button('View current alert','show-risk','','secondary'):''}</div></section></div>`;}
function settings(){return intro('Comfortable to read.<br>Clear to use.','Presentation preferences for this browser prototype.')+`<section class="card"><div class="setting-row"><div><h2>Larger text</h2><p>Increase reading sizes across the interface.</p></div><button class="switch" role="switch" aria-label="Larger text" aria-checked="${state.large}" data-action="large">${state.large?'On':'Off'}</button></div><div class="setting-row"><div><h2>Higher contrast</h2><p>Strengthen text, borders and control outlines.</p></div><button class="switch" role="switch" aria-label="Higher contrast" aria-checked="${state.contrast}" data-action="contrast">${state.contrast?'On':'Off'}</button></div></section><p style="font-size:14px;margin-top:20px">These are new prototype presentation controls. They have not been evaluated in the original usability study.</p>`;}
const views={appliances,safety};
function render(focus=false){document.body.classList.toggle('large',state.large);document.body.classList.toggle('contrast',state.contrast);$('#main').innerHTML=views[view]();$('#view-label').textContent={dashboard:'OVERVIEW',cooking:'COOKING',appliances:'APPLIANCES',safety:'SAFETY',settings:'ACCESSIBILITY'}[view];document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.closest('nav')){if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}});$('.topbar [data-action="large"]').setAttribute('aria-pressed',state.large);renderDialog();if(focus&&!state.modal)$('#main').focus({preventScroll:true});}
function renderDialog(){const d=$('#dialog');if(!state.modal){if(d.open){d.close();returnFocus?.focus();}return;}let title='',text='',actions='';switch(state.modal){case 'shutdown':title='Turn off your kitchen?';text='Choose full shutdown or standby. Standby keeps safety monitoring, the refrigerator, and an oven keeping food warm active.';actions=button('Turn off all','all-off','','danger')+button('Use standby','mode','data-value="standby"','secondary')+button('Cancel','cancel','','secondary');break;case 'unattended':title='Turn off the cooktop?';text='The kitchen has been unattended. Heat is already Low. With no response, the cooktop turns off after 30 seconds.';actions=button('Turn off now','confirm-off');break;case 'seasoning':title='Seasoning record';text=`<table><thead><tr><th>Seasoning</th><th>Additions</th><th>Demo time</th></tr></thead><tbody><tr><td>Salt</td><td>${state.salt}</td><td>${state.saltTimes.join(' · ')||'—'}</td></tr><tr><td>Soy sauce</td><td>${state.soy}</td><td>${state.soyTimes.join(' · ')||'—'}</td></tr><tr><td>Sugar</td><td>Not used</td><td>—</td></tr></tbody></table>`;actions=button('Done','cancel');break;case 'sos':title='Do you need urgent help?';text='The original flow requests assistance automatically after 10 seconds. This demo will only simulate a connection.';actions=button('Request help now','help','','danger')+button('Accidental tap · go back','cancel','','secondary');break;case 'risk':title={gas:'Gas alert detected',water:'Water detected',fall:'Possible fall detected'}[state.event]||'Kitchen alert';text='The original scenario cuts appliance power and requests help. '+(state.call==='connected'?'Simulated assistance connected.':'Simulated assistance is being requested.');actions=button('Simulate risk cleared','clear-risk','','secondary');break;case 'resolved':title='Risk-cleared scenario';text='The original flow returns to the dashboard after 5 seconds. Appliances remain off until restarted manually.';actions=button('Return to kitchen','cancel','','secondary');break;case 'call':case 'family':title=state.call==='connected'?'Connected · simulation':state.modal==='family'?'Contacting family…':'Requesting assistance…';text='Kitchen status is shared in the original flow. No real call or message is sent by this prototype.';actions=button('End demo call','cancel','','secondary');break;}
d.innerHTML=`<p class="eyebrow">${['risk','sos'].includes(state.modal)?'ASSISTANCE':'KITCHEN COMPANION'}</p><h2 id="dialog-title">${title}</h2><div>${text.startsWith('<table')?text:`<p>${text}</p>`}</div>${state.countdown?`<div class="count" role="timer" aria-label="${state.countdown} seconds remaining">${state.countdown}<span style="font-size:16px"> seconds</span></div>`:''}<div class="actions">${actions}</div>`;if(!d.open)d.showModal();}
const scenarioDefs=[['Pan detected','pan'],['Ignition','ignite'],['Pan hot','warm'],['Oil splatter','oil'],['Pan drying','dry'],['Kitchen unattended','unattended'],['Extended absence · 30s','long-away'],['Salt added','salt'],['Soy sauce added','soy'],['Oven · steaming','oven','Steaming · 160°C'],['Oven · keeping warm','oven','Keeping warm'],['Oven · ready to remove','oven','Ready to remove'],['Dishwasher · washing','dishwasher','Washing'],['Dishwasher · drying','dishwasher','Drying'],['Dishwasher · complete','dishwasher','Ready to unload'],['Gas alert','risk','gas'],['Water alert','risk','water'],['Fall alert','risk','fall']];
$('#scenarios').innerHTML=scenarioDefs.map(([label,type,value])=>`<button data-action="${type}" ${value?`data-value="${value}"`:''}>${label}</button>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view){view=b.dataset.view;render(true);return;}if(b.dataset.action){returnFocus=b;let a={type:b.dataset.action,value:b.dataset.value,device:b.dataset.device};if(a.type==='show-risk'){state.modal='risk';}else{state=E.reduce(state,a);if(a.type==='mode')state.modal=null;}if(a.type==='reset'||a.type==='clear-risk')view='appliances';if(['pan','ignite','warm','oil','dry','unattended','long-away','salt','soy','oven','dishwasher'].includes(a.type))view='appliances';if(a.type==='risk')view='safety';$('#announcement').textContent=state.logs[0]||'Display preference updated.';render();if(!state.modal){const match=document.querySelector(`button[data-action="${a.type}"]${a.value?`[data-value="${a.value}"]`:''}${a.device?`[data-device="${a.device}"]`:''}`);if(match)match.focus({preventScroll:true});}}});
$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if(['risk','unattended'].includes(state.modal))return;state=E.reduce(state,{type:'cancel'});render();});
setInterval(()=>{if(state.countdown>0){const old=state.countdown;const modal=state.modal;state=E.reduce(state,{type:'tick'});if(old===1||modal!==state.modal){render();$('#announcement').textContent=state.logs[0]||'Countdown complete.';}else{const count=$('#dialog .count');if(count){count.firstChild.textContent=state.countdown;count.setAttribute('aria-label',state.countdown+' seconds remaining');}}}},1000);
render();

// Portfolio scenarios replay the same reducer; no real sensors or calls are connected.
const portfolioScenes={cooking:[{type:'pan'},{type:'ignite'}],away:[{type:'pan'},{type:'ignite'},{type:'heat',value:'High'},{type:'unattended'},{type:'long-away'}],seasoning:[{type:'pan'},{type:'ignite'},{type:'salt'},{type:'salt'},{type:'salt'},{type:'seasoning'}],fall:[{type:'risk',value:'fall'}],family:[{type:'family'}]};
function showPortfolioScene(name){if(!portfolioScenes[name]&&name!=='normal')return;state=E.initial();view=name==='fall'||name==='family'?'safety':'appliances';for(const action of portfolioScenes[name]||[])state=E.reduce(state,action);$('#announcement').textContent=state.logs[0]||'All normal.';render();}
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='aiger-scene')showPortfolioScene(event.data.scene);});
const initialScene=new URLSearchParams(location.search).get('scene');if(initialScene)showPortfolioScene(initialScene);
